pipeline {
    agent any
    stages {
        stage('Build') { 
            steps {
                sh 'mvn -B -DskipTests -f .../build-simple-java-maven-app/pom.xml clean package' 
            }
        }
    }
}