pipeline {
    agent any
    def pomfilepath= build-simple-java-maven-app/pom.xml
    stages {
        stage('Build') { 
            steps {
                sh 'mvn -B -DskipTests clean package' 
            }
        }
    }
}