pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'cd build-simple-node-js-react-npm-app && npm install'
            }
        }
        stage('Test') {
            steps {
                sh 'chmod -R 777 build-simple-node-js-react-npm-app/jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') { 
            steps {
                sh 'chmod -R 777 build-simple-node-js-react-npm-app/jenkins/scripts/deliver.sh' 
                input message: 'Finished using the web site? (Click "Proceed" to continue)' 
                sh 'chmod -R 777 build-simple-node-js-react-npm-app/jenkins/scripts/kill.sh' 
            }
        }
    }
}