pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'cd build-simple-node-js-react-npm-app && npm install'
            }
        }
        stage('Test') { 
            steps {
                sh 'chmod -R 777 build-simple-node-js-react-npm-app/jenkins/scripts/test.sh' 
            }
        }
    }
}