pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'cd build-simple-java-maven-app && mvn -B -DskipTests clean package'
            }
        }
        stage('Test') { 
            steps {
                sh 'cd build-simple-java-maven-app && mvn test' 
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml' 
                }
            }
        }
    }
}