pipeline {
    agent any
    stages {
        stage('Build') { 
            steps {
                sh 'cd build-simple-java-maven-app && mvn -B -DskipTests clean package'
            }
        }
    }
}