pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {
            steps {
                sh 'cd build-simple-java-maven-app && mvn -B -DskipTests clean package'
            }
        }
        stage('Test') { 
            steps {
                sh 'cd build-simple-java-maven-app && mvn test' 
            }
            post {
                always {
                    junit 'build-simple-java-maven-app/target/surefire-reports/*.xml' 
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './deliver.sh'
            }
        }
    }
}